# Generated by Django 4.2.7 on 2023-11-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='blog_image1',
            field=models.ImageField(default='default.jpg', upload_to='blog_pics'),
        ),
    ]
