# Generated by Django 4.2.7 on 2023-11-16 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_blog_image1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_image',
            field=models.ImageField(default='blog_pics/new_post.jpg', upload_to='blog_pics/', verbose_name='blog-image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='blog_image1',
            field=models.ImageField(default='blog_pics/default.jpg', upload_to='blog_pics/'),
        ),
    ]
