# Generated by Django 4.2.7 on 2023-11-16 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_post_blog_image_alter_post_blog_image1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='blog_image1',
        ),
    ]
