# Generated by Django 4.2.7 on 2023-11-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_post_blog_image1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_image',
            field=models.ImageField(default='new_post.jpg', upload_to='blog_pics/', verbose_name='blog-image'),
        ),
    ]
